---
title: "Data package creation for Coastal Bird monitoring at Boston Harbor Islands NRA (BOHA)"
author: "*Compiled on `r Sys.time()` by `r Sys.info()['user']` using `r R.Version()$version.string`*"
output: 
  html_document:
    highlight: textmate
    number_sections: yes
    theme: united
    toc: yes
    toc_depth: 3
    toc_float: yes
---


```{r intro, results='markup', echo=F, include=FALSE}
cat("\\newpage")

library(NETNCoastalBirds)
library(tidyverse)
library(magrittr)
library(RODBC)
library(lubridate)
library(dplyr)

```

# Create Events_All

```{r events, results='markup', echo=F, include=FALSE}

con <- RODBC::odbcConnect("NETNCB")# establish connection to DB
    
events <- RODBC::sqlFetch(con, "tbl_Events")
 
RODBC::odbcClose(con)

# drop extra columns
events <- events[, !colnames(events)%in%c("Imported_By", "Imported_Time", "Imported_Notes")] 

# rearrange columns
events <- events[,c(3:26,1,2)]
```

# Create Survey Incubation

```{r Incubation, results='markup', echo=F, include=FALSE}


incub <- GetIncubationData()

```

# Create Survey_Nest

```{r Survey_Nest, results='markup', echo=F, include=FALSE }

ground.nests <- GetNestData()


```

# Create Creche Survey

```{r creche, results='markup', echo=F, include=FALSE }


creche<-GetCrecheData()

```

# Create AMOY Survey

```{r AMOY, results='markup', echo=F, include=FALSE }

AMOY<-GetAMOYData()

# Alternative way to creating qry_Dataset_5_Survey_AMOY without using NETNCoastalBirds function:

# pull tables from Access
con <- RODBC::odbcConnect("NETNCB") # connect to DB

event <- RODBC::sqlFetch(con, "tbl_Events")
group <- RODBC::sqlFetch(con, "tbl_Group")
group_obs <- RODBC::sqlFetch(con, "tbl_Group_Observations")
species <- RODBC::sqlFetch(con, "tlu_species")

RODBC::odbcClose(con)  # close connection

# join tables and filter
temp.amoy <- left_join(event, group, by = c("pk_EventID" = "fk_EventID"))%>%
  filter(., Species_Code == "AMOY" & Obs_Type == "Group")%>%
  left_join(., group_obs, by = c("pk_GroupID" = "fk_GroupID"))%>%
  inner_join(., species, by = "Species_Code")

# Add date information
temp.amoy$Date <- ymd(temp.amoy$Date) #convert to date
temp.amoy$Year <- year(temp.amoy$Date) #Create year variable
temp.amoy$Month <- month(temp.amoy$Date) #Create month variable

# Remove date from the time columns
temp.amoy$Start_Time<-substr(temp.amoy$Start_Time,12,19)
temp.amoy$End_Time<-substr(temp.amoy$End_Time,12,19)
temp.amoy$Group_Time<-substr(temp.amoy$Group_Time,12,19)

# Edit column names
names(temp.amoy) <- gsub(x = names(temp.amoy), pattern = 'pk_', replacement = '')

# Subset columns for final df  
amoy_raw <- select(temp.amoy, Park, Survey_Agency, Survey_Class, Survey_Type, 
                   Date, Month, Year, Start_Time, End_Time, Island, Segment, 
                   Recorder, Observer, Wind_Direction, Wind_Speed, Air_Temp_F, 
                   Cloud_Perc, Tide_Stage, Survey_Complete, Survey_MultiPart,
                   Survey_Duplicate, Survey_Primary, Survey_Notes, 
                   c_TargetSpp_Group, Checked, DPL, Data_Source, Obs_Type, 
                   Species_Code, CommonName, Group_Count, Group_Coords, 
                   Group_Notes, Group_Time, Species_Unit, Unit_Count, 
                   EventID, GroupID, GroupObsID)


```

# Create AMOY PIPL Summary - qry 6

```{r}
## connect to DB:
con <- RODBC::odbcConnect("NETNCB")
  
###################### Import data and lookup tables used for the query 
#"tbl_Summary_Spp_AMOY_PIPL" and "tlu_Species     
  
# import dataframes of each tables within the DB
summary <- RODBC::sqlFetch(con, "tbl_Summary_Spp_AMOY_PIPL")
species <- RODBC::sqlFetch(con, "tlu_Species")
  
# Close connection
RODBC::odbcClose(con)

# Bind tables, filter to desired species
temp.AMOYPIPL <- full_join(species, summary, by = c('Species_Code' = 'Species'))%>%
  filter(., Species_Code == 'AMOY'| Species_Code == 'PIPL')

# subset df to final columns for exporting
raw.AMOYPIPL <- select(temp.AMOYPIPL, "CommonName", "Species_Code", "Location",
                       "Survey_Year", "Pair_Count_MAwindow", "Reporting_Agency",
                       "DPL", "Notes")

```

# Create Tern Summary - qry 7

```{r}
## connect to DB:
con <- RODBC::odbcConnect("NETNCB")

###################### Import data and lookup tables used for the query   
#"tbl_Summary_Spp_Terns","tlu_Species","tlu_Tern_Summary_Method", "tlu_Tern_Summary_Productivity"     

# import dataframes of each tables within the DB
summary <- RODBC::sqlFetch(con, "tbl_Summary_Spp_Terns")
species <- RODBC::sqlFetch(con, "tlu_Species")
method <- RODBC::sqlFetch(con, "tlu_Tern_Summary_Method")
Productivity <- RODBC::sqlFetch(con, "tlu_Tern_Summary_Productivity")

# Close connection
RODBC::odbcClose(con)

# Bind tables, filter to tern species, and remove NA's from DPL column
temp.terns <- left_join(summary, species, by = c('Species' = 'Species_Code'))%>%
  full_join(., method, by =c('Method' = 'Code'))%>%
  full_join(., Productivity, by = c('Productivity' = 'Code'))%>%
  filter(., Species == 'COTE'| Species == 'LETE'| Species == 'ROTE')%>%
  filter(!is.na(.$DPL))

# Rename some cols to match DB version
temp.terns%>%
  rename(Method_Code = Method, Method_Desc = Description.x, 
         Productivity_Code = Productivity, 
         Productivity_Desc = Description.y) -> temp.terns

# subset df to final columns for exporting
raw.terns <- select(temp.terns, "CommonName", "Species", "Location", 
                    "Survey_Year", "Count_MAwindow", "Method_Code",
                    "Method_Desc", "Productivity_Code", "Productivity_Desc",
                    "Reporting_Agency", "DPL", "Notes")

```

# Create Surveillance Survey - qry 8

```{r}
## connect to DB:
con <- RODBC::odbcConnect("NETNCB")

###################### Import data and lookup tables used for the query   
#"tbl_Events","tlu_Species","tbl_Observations"      

# import dataframes of each tables within the DB
events <- RODBC::sqlFetch(con, "tbl_Events")
species <- RODBC::sqlFetch(con, "tlu_Species")
obs <- RODBC::sqlFetch(con, "tbl_Observations")

# Close connection
RODBC::odbcClose(con)

# Bind tables and filter to Surveillance surveys
temp.surv <- left_join(events, obs, by = c('pk_EventID' = 'fk_EventID'))%>%
  inner_join(., species, by = 'Species_Code')%>%
  filter(., Survey_Type == 'Surveillance')

# Rename columns to match Access col names
temp.surv <- rename(temp.surv, 'Species_name' = 'CommonName')
names(temp.surv) <- gsub(x = names(temp.surv), pattern = 'pk_', replacement = '')

# Add time variables
temp.surv$Date  <- ymd(temp.surv$Date) #convert to date
temp.surv$year  <- year(temp.surv$Date) #Create year variable
temp.surv$month <- month(temp.surv$Date) #Create month variable

## subset df to final columns for exporting
raw.surv <- select(temp.surv, "Park", "Survey_Agency", "Survey_Class", 
                   "Survey_Type", "Date", "Island", "Segment", 
                   "Observer", "Obs_Type", "Species_Code", 
                   "Species_name", "Species_Unit", "Unit_Count", 
                   "Obs_Coords", "Obs_Notes", "Obs_Time", "EventID", 
                   "ObservationID", "year", "month")

```

# Create Incidental Summary - qry 9

```{r}
## connect to DB:
con <- RODBC::odbcConnect("NETNCB")

###################### Import data and lookup tables used for the query   
#"tbl_Events","tlu_Species","tbl_Observations"      

# import dataframes of each tables within the DB
events <- RODBC::sqlFetch(con, "tbl_Events")
species <- RODBC::sqlFetch(con, "tlu_Species")
obs <- RODBC::sqlFetch(con, "tbl_Observations")

# Close connection
RODBC::odbcClose(con)

# Bind tables, filter to Incidental observations, and remove Surveillance surveys
temp.incid <- left_join(events, obs, by = c('pk_EventID' = 'fk_EventID'))%>%
  inner_join(., species, by = 'Species_Code')%>%
  filter(., Obs_Type == 'Incidental',
         Survey_Type != 'Surveillance')

# Rename columns to match Access col names
temp.incid <- rename(temp.incid, 'Species_name' = 'CommonName')
names(temp.incid) <- gsub(x = names(temp.incid), pattern = 'pk_', replacement = '')

# Add time variables
temp.incid$Date  <- ymd(temp.incid$Date) #convert to date
temp.incid$year  <- year(temp.incid$Date) #Create year variable
temp.incid$month <- month(temp.incid$Date) #Create month variable

## subset df to final columns for exporting
raw.incid <- select(temp.incid,"Park", "Survey_Agency", "Survey_Class",
                         "Survey_Type", "Date", "Island", "Segment", 
                         "Observer", "Obs_Type", "Species_Code", 
                         "Species_name", "Species_Unit", "Unit_Count", 
                         "Obs_Coords", "Obs_Notes", "Obs_Time", 
                         "EventID", "ObservationID", "year", "month")

```

