#' @include SumIncubation.R
#' @include SumNestSurveys.R
#' @include CrecheSum.R
#' 
#' @title BoxPlot of coastal bird survey data
#'
#' @import ggplot2 
#' @importFrom lubridate is.Date
#'
#' @description Boxplot of bird detections by Island. 
#' @param data A \code{data.frame}  of coastal bird observations summarized for plotting. Typically from \code{\link{SumIncubation}}, \code{\link{CrecheSum}}, or \code{\link{SumNestSurveys}}.
#' @param raw_count \code{TRUE} or \code{FALSE}. Plot effort-adjusted (default) or raw count data?
#' @param island A vector of island names (e.g., "Calf"). To view surveys summed across all islands, use 
#' "All Islands". When using "All Islands" you need to supply agrument to facet (such as "variable").
#' @param species  Character. A  vector of species name codes, e.g. "BCNH"
#' @param var Character. Select a variable to plot, typically a life stage (e.g., Eggs, Nests, Creche size). Defaults to all values.
#' @param scale Character. Convert to log scale by entering "log".
#' @param year Numeric. Calendar year(s) to view data by. Useful when wanting to view seasonal survey data in a year.
#' @param stat Character. Specify type of statistic to plot. Defaults to plotting the sum, but you can plot other
#' annual statistics by setting to "mean","max", or "min" when the \code{df} is generated by \code{\link{SumIncubation}} or \code{\link{CrecheSum}} functions.
#' @param facet Character. Plot the data into separate facets by Island, Species, or variable. Defaults to Island. If \code{overlay = "island"} set \code{facet} to "CommonName", "Species_Code" , "FullLatinName" or "variable".
#' @param overlay Character. Defaults to \code{"var"} which overlays data by lifestage. Enter \code{"species"} to overlay time series 
#' by species when \code{data} contains multiple species. Enter \code{"island"} to overlay data by island. When overlaying by island and 
#' when multiple species are in \code{data}, denote \code{facet} as "CommonName", "Species_Code" or "FullLatinName".
#' In cases where the \code{data} has multiple life stages (e.g., nests), provide argument to \code{var} to plot only one life stage at a time.
#' @param print Logical. Defaults to \code{TRUE} to print plot. If \code{FALSE} outputs graph data as \code{y2$data} object
#' @param  plot_title Logical. Add a caption to the plot? Defaults to \code{TRUE}.
#' @param legend Logical. Add legend. Defaults to \code{FALSE}.
#' @param Y_scale Character. Should y-scale of individual facets be on the same scale (default, "fixed") or not ("free_y")?
#' @return Outputs a ggplot boxplot of species detections by Island with indivudual 
#' @seealso \url{https://www.nps.gov/im/netn/coastal-birds.htm}
#' @examples 
#' 
#' @export

BoxPlotBirds<-function(data, raw_count= FALSE, species= NA, island=NA, year= NA, stat=NA,
                    scale="norm", facet= "Island", var= NA, overlay = "var", print= TRUE, 
                    plot_title = TRUE, legend= FALSE, Y_scale ="fixed"){
 
  # Set up data from graphdata for plotting
  
  # subset data
  graphdata <- data
  
  # check to see if df has "stat" and if stat has been specified
  if("stat" %in% colnames(graphdata) & anyNA(stat)){
    cat("WARNING: Please supply argument to stat to avoid incorrectly plotting multiple statistics")
  }
  
  if(!anyNA(species)) graphdata<-graphdata[graphdata$Species_Code %in% species, ]
  
  if(!anyNA(island)) graphdata <- graphdata[graphdata$Island %in% island, ]
  
  if(!anyNA(var)) graphdata<-graphdata[graphdata$variable %in% var, ]
  
  if(!anyNA(year)) graphdata<-graphdata[graphdata$year %in% year, ] # for subsetting data ByDate
  
  if(facet == "Island") graphdata <- graphdata[!graphdata$Island %in% "All Islands", ]# remove All islands
  
  #if(!anyNA(method)) graphdata <- graphdata[!graphdata$Count_Method %in% "Direct Count", ]
  
  # select summary data you want to plot from dataframe with a column "stat" (sum, min, mean, max)
  
  if(!anyNA(stat)) graphdata<-graphdata[graphdata$stat %in% stat, ]
  
  ### SETUP PLOTS 
  
  ## what value should be plotted? 
  #The raw counts (value) or effort-adjusted counts (valuePerSurveySize)
  if(!raw_count){
    # just rename the vector to grab effort adjusted counts
    graphdata$value<- graphdata$valuePerSurveySize
  }
  
  %>% mutate(shape = case_when(
    year == params$year ~ "8",
    .default = "19" )) %>% 
      mutate(color = case_when(
        year == params$year ~ "red",
        .default = "black" ))
  
  
  # Create Plot
  
  ggplot(data= filter(dcco, stat == "max"), aes(x= Island, y= value, fill= Island, group= Island)) +
    geom_boxplot(alpha= 0.3, notch= F, outliers = TRUE, outlier.shape = 19,)+ 
    geom_jitter(aes(shape = shape, color= color), size= 3) +
    scale_color_manual(values = c("black", "red"))+ 
    scale_shape_manual(values = c(19, 8))+ 
    theme_bw()+
    theme(legend.position = "none")+
    labs(y = "Incubating Adults")+
    ggtitle(paste0("Variation in counts of incubating DCCO adults from 2007 to ", params$year, "by Island. The red asterisks denotes current year count."))+
    theme(axis.text.y = element_text(color="black", vjust= 0.5, size = 16)) +
    theme(axis.text.x = element_text(angle = 0,  vjust=0,size = 12 )) +
    theme(axis.text.y = element_text(size = 12 )) +
    theme(strip.text.x= element_text(size=12, face=c("bold.italic"))) +
    theme(axis.title.x =element_text(size = 16, face ="bold", vjust= 0, debug=F)) +
    theme(axis.title.y =element_text(size = 16, face ="bold", vjust= 1, debug=F)) +
    theme(panel.background =  element_rect(fill="white", colour="black")) +
    theme(panel.grid.major = element_line(colour = "grey90")) +
    theme(plot.title=element_text(size=12, vjust=2, face= "bold")) +
    theme(strip.background= element_rect(size=10, color="gray" ))
  
  
   
}
  