#' @include SumIncubation.R
#' @include SumNestSurveys.R
#' @include CrecheSum.R
#' 
#' @title Plot coastal bird survey data
#'
#' @import ggplot2 
#' @importFrom lubridate is.Date
#'
#' @description Plots bird detections over time.
#' @param data A \code{data.frame}  of coastal bird observations summarized for plotting. Typically from \code{\link{SumIncubation}}, \code{\link{CrecheSum}}, or \code{\link{SumNestSurveys}}.
#' @param raw_count \code{TRUE} or \code{FALSE}. Plot effort-adjusted (default) or raw count data?
#' @param island A vector of island names (e.g., "Calf"). To view surveys summed across all islands, use 
#' "All Islands". When using "All Islands" you need to supply agrument to facet (such as "variable").
#' @param species  Character. A  vector of species name codes, e.g. "BCNH"
#' @param var Character. Select a variable to plot, typically a life stage (e.g., Eggs, Nests, Creche size). Defaults to all values.
#' @param scale Character. Convert to log scale by entering "log".
#' @param year Numeric. Calendar year(s) to view data by. Useful when wanting to view seasonal survey data in a year.
#' @param stat Character. Specify type of statistic to plot. Defaults to plotting the sum, but you can plot other
#' annual statistics by setting to "mean","max", or "min" when the \code{df} is generated by \code{\link{SumIncubation}} or \code{\link{CrecheSum}} functions.
#' @param facet Character. Plot the data into separate facets by Island, Species, or variable. Defaults to Island. If \code{overlay = "island"} set \code{facet} to "CommonName", "Species_Code" , "FullLatinName" or "variable".
#' @param overlay Character. Defaults to \code{"var"} which overlays data by lifestage. Enter \code{"species"} to overlay time series 
#' by species when \code{data} contains multiple species. Enter \code{"island"} to overlay data by island. When overlaying by island and 
#' when multiple species are in \code{data}, denote \code{facet} as "CommonName", "Species_Code" or "FullLatinName".
#' In cases where the \code{data} has multiple life stages (e.g., nests), provide argument to \code{var} to plot only one life stage at a time.
#' @param print Logical. Defaults to \code{TRUE} to print plot. If \code{FALSE} outputs graph data as \code{y2$data} object
#' @param  plot_title Logical. Add a caption to the plot? Defaults to \code{TRUE}.
#' @param legend Logical. Add legend. Defaults to \code{FALSE}.
#' @param Y_scale Character. Should y-scale of individual facets be on the same scale (default, "fixed") or not ("free_y")?
#' @return Outputs a ggplot graph of species detections over time.
#' @seealso \url{https://www.nps.gov/im/netn/coastal-birds.htm}
#' @examples 
#' #Incubation surveys by year
#' dcco <- SumIncubation(time = "year", species = "DCCO",stat ="mean")
#' PlotBirds(dcco)
#' 
#' # Incubation surveys by year of multiple species
#' incub<-SumIncubation(time = "year", species = c("DCCO", "HERG", "GBBG"))
#' PlotBirds(incub, overlay= "species", raw_count= FALSE, stat ="mean", plot_title ="no")
#' PlotBirds(incub, overlay= "island", raw_count= FALSE, stat ="mean", plot_title ="no", facet="CommonName", legend= T) 
#' # Incubation surveys by date to view repeat effort
#' gbbg <- SumIncubation(time = "date", species = "GBBG")
#' PlotBirds(gbbg, year= "2012", legend =TRUE, stat ="sum")
#' 
#' # Creche surveys by date; typically to view efforts in a single season
#' creche <- CrecheSum(time ="date")
#' # View survey counts in 2018
#' PlotBirds(creche, year = "2018", stat= "sum")
#' # surveys summed across all islands
#' PlotBirds(creche, year = "2018", island= "All Islands", facet= "variable", legend = TRUE, stat= "sum")
#' 
#' # Nest surveys
#' nests <- SumNestSurveys(time= "year", species = "BCNH")# annual counts of BCNH
#' PlotBirds(nests, var = "Nests")
#' PlotBirds(nests, island = "All Islands", facet= "variable", raw_counts= FALSE)
#' PlotBirds(nests, var= "EggsPerNest", legend =TRUE)
#' 
#' # Nest surveys of all species
#' nests<-SumNestSurveys(time= "year")
#' PlotBirds(nests, var = "Nests", overlay= "species")
#' 
#' @export

PlotBirds<-function(data, raw_count= FALSE, species= NA, island=NA, year= NA, stat=NA,
                    scale="norm", facet= "Island", var= NA, overlay = "var", print= TRUE, 
                    plot_title = TRUE, legend= FALSE, Y_scale ="fixed"){

  
  # subset data
  graphdata <- data
  
  # check to see if df has "stat" and if stat has been specified
  if("stat" %in% colnames(graphdata) & anyNA(stat)){
    cat("WARNING: Please supply argument to stat to avoid incorrectly plotting multiple statistics")
  }
  
  if(!anyNA(species)) graphdata<-graphdata[graphdata$Species_Code %in% species, ]
  
  if(!anyNA(island)) graphdata <- graphdata[graphdata$Island %in% island, ]
  
  if(!anyNA(var)) graphdata<-graphdata[graphdata$variable %in% var, ]
  
  if(!anyNA(year)) graphdata<-graphdata[graphdata$year %in% year, ] # for subsetting data ByDate
  
  if(facet == "Island") graphdata <- graphdata[!graphdata$Island %in% "All Islands", ]# remove All islands
  
  #if(!anyNA(method)) graphdata <- graphdata[!graphdata$Count_Method %in% "Direct Count", ]
  
  # select summary data you want to plot from dataframe with a column "stat" (sum, min, mean, max)

  if(!anyNA(stat)) graphdata<-graphdata[graphdata$stat %in% stat, ]
  
  ### SETUP PLOTS 
  
  ## what value should be plotted? 
  #The raw counts (value) or effort-adjusted counts (valuePerSurveySize)
  if(!raw_count){
    # just rename the vector to grab effort adjusted counts
    graphdata$value<- graphdata$valuePerSurveySize
  }
  
  if(scale == "log"){ graphdata$value <-log(graphdata$value)}
  
  #### overlay control ####
  # overlay by variable (life stage)
  if(overlay == "var"){
     y2 <- ggplot(graphdata,aes(x=time, y= value, color= variable, group= variable))+
                  geom_point(size = 2) +geom_line() + scale_colour_viridis_d(option="D")
}
  if (overlay == "species"){
        # overlay  by CommonName
    y2<-ggplot(graphdata, aes(x=time, y= value, colour= CommonName,group= CommonName))+
    geom_point()+ 
    geom_line()+ scale_colour_viridis_d(option="D")+
    ggtitle(paste0(if(!anyNA(var)) var, "Counts of ",graphdata$variable[1], " per ", facet))
  }
  
  if (overlay == "island"){
    # overlay  Islands
    y2<-ggplot(graphdata, aes(x=time, y= value, colour= Island,group= Island))+
      geom_point()+ 
      geom_line()+ scale_colour_viridis_d(option="D")+
      ggtitle(paste0(if(!anyNA(var)) var, "Counts of ",graphdata$variable[1], " per ", facet))
  }

 
## Setup y-axis labels
  
  if(!raw_count & scale =="log"){
    y2<-(y2+ labs(y = paste0("log(Number Detected) per ", graphdata$Survey_Units[1]), x= ""))}
  
  else if(!raw_count & scale =="norm"){
    y2<-(y2+ labs(y = paste0("Number Detected per ", graphdata$Survey_Units[1]), x= ""))}
  
  else if(raw_count & scale =="log"){
    y2<-(y2+ labs(y = "log(Number Detected) per Survey", x= ""))}
  
  else if(raw_count & scale =="norm"){
    y2<-(y2+ labs(y = "Number Detected per Survey", x= ""))}
  
  
### ADD FACETING 
  if(!anyNA(facet)) {
    y2 <- (y2 + facet_wrap(facet, scales = Y_scale, ncol = 3 ))
    
  }
#### TOGGLE plot title (above plot) 
  if(plot_title){
    
    if(scale == "log"){
      y2<- (y2 + ggtitle(paste0("Log-transformed annual counts of ", graphdata$CommonName[1]," ", if(!anyNA(var)) var, " per ", facet)))
  }else{
    y2<- (y2 + ggtitle(paste0("Annual counts of ", graphdata$CommonName[1]," ", if(!anyNA(var)) var," per ", facet)))
  }
    }else{
      y2<- y2
    }

  ###DEFINE THEME
  y2 <- (y2 +
         {if (is.numeric(graphdata$time)) scale_x_continuous(breaks= seq(min(graphdata$time),max(graphdata$time),2))}+
         {if(is.Date(graphdata$time)) scale_x_date(date_minor_breaks = "1 day")} +  
         {if(legend) theme(legend.position = "top") + theme(legend.key = element_blank()) + 
             theme(legend.title = element_blank())+ theme(legend.text = element_text(size = 12,face = "bold"))}+
         {if(!legend)theme(legend.position = "none")}+
         theme(axis.text.y = element_text(color="black", vjust= 0.5, size = 16)) +
         theme(axis.text.x = element_text(angle = 0,  vjust=0,size = 12 )) +
          theme(axis.text.y = element_text(size = 12 )) +
         theme(strip.text.x= element_text(size=12, face=c("bold.italic"))) +
         theme(axis.title.x =element_text(size = 16, face ="bold", vjust= 0, debug=F)) +
         theme(axis.title.y =element_text(size = 16, face ="bold", vjust= 1, debug=F)) +
         theme(panel.background =  element_rect(fill="white", colour="black")) +
         theme(panel.grid.major = element_line(colour = "grey90")) +
         theme(plot.title=element_text(size=12, vjust=2, face= "bold")) +
         theme(strip.background= element_rect(size=10, color="gray" )))
  
#### CHOOSE TO PRINT ON EXECUTION OR CREATE OBJECT; THE LATTER HELPFUL WHEN LOOPING  
  
  if(print){
    
    suppressWarnings(print(y2))
    
  }
  else{
  
  return(y2)
    }
}
